[package]
name = "income-calc"
version = "0.1.0"
edition = "2021"

[dependencies]
prettytable-rs = "^0.10"
round = "0.1.2"
console = "0.15.10"
colored = "2.2.0"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
