[package]
name = "income-calc"
version = "0.1.0"
edition = "2021"

[dependencies]
prettytable-rs = "^0.10"
round = "0.1.2"
console = "0.15.10"
colored = "3.0.0"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
chrono = { version = "0.4.39", features = ["serde"] }
